### ISSUE TITLE
23-02-14 부하 테스트

### ISSUE THREAD

**Issue by kimdev0206** [WithBible/withbible-server#9]
클라우드 환경(`cloudtype`, 메모리: `512MB`)에 부하테스트를 통해 응답시간이 급격히 늘어나다가 WAS가 죽고 ,
그 이후 요청에는 응답을 하지 못하는 상황을 감지하였다.

- 부하는 2단계로 이루어진다.
  ```
  1단계는 5초 동안 초당 1명의 가상 사용자를 생성한다.
  2단계는 10초 동안 1명의 가상 사용자를 30명으로 높인다.
  ```
  > _이때, 30명의 가상 사용자는 모두 동일한 계정 및 동일한 세션을 사용한다._
  >
  >_시나리오가 어색하지 않게 수정이 필요하다._
  > 
  >   ```
  >   (방안A) 30명의 가상 사용자가 모두 다른 계정
  >   (방안B) 30명의 가상 사용자가 동일한 계정으로 중복 로그인
  >   ```

  - [ ] #13

- 로컬 환경(사용가능한 메모리: `1GB`)은 발생하지 않았다.

다음은 WAS가 죽은 이후, 145개 요청을 처리하지 못한 지표이다.

```bash
--------------------------------
Summary report @ 16:01:08(+0900)
--------------------------------

errors.ETIMEDOUT: .............................................................. 145
http.codes.200: ................................................................ 611
http.codes.201: ................................................................ 10
http.request_rate: ............................................................. 20/sec
http.requests: ................................................................. 766
http.response_time:
  min: ......................................................................... 45
  max: ......................................................................... 9998
  median: ...................................................................... 5378.9
  p95: ......................................................................... 8024.5
  p99: ......................................................................... 9607.1
http.responses: ................................................................ 621
vusers.completed: .............................................................. 10
vusers.created: ................................................................ 155
vusers.created_by_name.퀴즈: ................................................... 155
vusers.failed: ................................................................. 145
vusers.session_length:
  min: ......................................................................... 1228.1
  max: ......................................................................... 22096.3
  median: ...................................................................... 1495.5
  p95: ......................................................................... 19737.6
  p99: ......................................................................... 19737.6
```

**Comment by yongki150** [comment]
해당 링크의 최종 답변은 다음과 같고,
> _현재 제공하는 제한적인 CPU/메모리(0.5vCore/512MB) 로 OOM(Out of memory) 이 발생하며 다른 문제도 함께 발생했을 수도 있을 것 같습니다._ 

해당 플랫폼에서 유료 기능이 생겨 하드웨어 자원을 늘려보고도 이슈가 지속된다면, 또 다른 방안을 생각해보아야한다.

**Comment by yongki150** [comment]
해당 플랫폼 측에서 유료 기능 업데이트 전까지 한시적으로 리소스를 추가해주었다.

> _512MB 메모리 → 4GB 메모리_

**Comment by yongki150** [comment]
로컬 환경에서도 동일한 이슈가 발생하였다.
즉, 리소스 문제가 아닌 것을 알 수 있다.

**Comment by yongki150** [comment]
2가지를 수행해볼 수 있다.

1. 클러스터링 기법을 통해 서버를 여러 개 실행하는 것이다.
2. 반복적으로 가져오는 데이터를 캐싱하는 것이다.
    새로 도입된 `Sentry`의 Profiling 기능을 통해 Slowest Transactions을 감지하였고,
    ![image](https://github.com/WithBible/withbible-server/assets/53007747/056a180a-3f81-4e34-b177-de58272ccdb3)
    이 중 2번째 API는 빈번히 바뀌지 않는 데이터로 충분히 캐싱할 수 있는 코드이다.

***
> _조현영 (2020). Node.js 교과서 개정 2판. 서울: 길벗, 526._

**Comment by yongki150** [comment]
조치사항 2번을 수행한 것만으로도 트랜잭션 기간을 2배 가량 줄일 수 있었다.

<table>
<tr>
 <th>퀴즈 데이터 캐싱 전</th>
 <th>퀴즈 데이터 캐싱 후</th>
</tr>
<tr>
<td>

```
All VUs finished. Total time: 34 seconds

--------------------------------
Summary report @ 16:02:38(+0900)
--------------------------------

errors.ETIMEDOUT: .............................................................. 107
http.codes.200: ................................................................ 692
http.codes.201: ................................................................ 62
http.request_rate: ............................................................. 36/sec
http.requests: ................................................................. 861
http.response_time:
  min: ......................................................................... 45
  max: ......................................................................... 7225
  median: ...................................................................... 907
  p95: ......................................................................... 4231.1
  p99: ......................................................................... 6702.6
http.responses: ................................................................ 754
vusers.completed: .............................................................. 48
vusers.created: ................................................................ 155
vusers.created_by_name.퀴즈: ..................................................... 155
vusers.failed: ................................................................. 107
vusers.session_length:
  min: ......................................................................... 1133.3
  max: ......................................................................... 12861.3
  median: ...................................................................... 3828.5
  p95: ......................................................................... 12213.1
  p99: ......................................................................... 12459.8
```
</td>
<td>

```
All VUs finished. Total time: 30 seconds

--------------------------------
Summary report @ 15:57:45(+0900)
--------------------------------

errors.ETIMEDOUT: .............................................................. 127
http.codes.200: ................................................................ 572
http.codes.201: ................................................................ 39
http.request_rate: ............................................................. 37/sec
http.requests: ................................................................. 738
http.response_time:
  min: ......................................................................... 46
  max: ......................................................................... 4744
  median: ...................................................................... 788.5
  p95: ......................................................................... 2836.2
  p99: ......................................................................... 4231.1
http.responses: ................................................................ 611
vusers.completed: .............................................................. 28
vusers.created: ................................................................ 155
vusers.created_by_name.퀴즈: ..................................................... 155
vusers.failed: ................................................................. 127
vusers.session_length:
  min: ......................................................................... 1430.8
  max: ......................................................................... 9721.6
  median: ...................................................................... 3464.1
  p95: ......................................................................... 7557.1
  p99: ......................................................................... 8520.7
```
</td>
</tr>
</table>

**Comment by yongki150** [comment]
하지만, 근본적인 원인은 해결하지 못했다. 

> _클라우드 환경(cloudtype(PaaS))에 부하테스트를 통해 처리소요시간이 급격히 늘어나다가 WAS가 죽고 ,
그 이후 요청에는 응답을 하지 못하는 상황을 감지하였다._

**Comment by yongki150** [comment]
https://github.com/WithBible/withbible-server/issues/9#issuecomment-1556498191 의 1번 및 2번을 수행함으로써 처리율은 높이고 (`82.79%` → `95.69%`), 응답 시간은 늘어나게 되었다.

```
All VUs finished. Total time: 40 seconds

--------------------------------
Summary report @ 15:53:49(+0900)
--------------------------------

errors.ETIMEDOUT: .............................................................. 43
http.codes.200: ................................................................ 844
http.codes.201: ................................................................ 104
http.codes.204: ................................................................ 8
http.request_rate: ............................................................. 34/sec
http.requests: ................................................................. 999
http.response_time:
  min: ......................................................................... 42
  max: ......................................................................... 9995
  median: ...................................................................... 2566.3
  p95: ......................................................................... 7557.1
  p99: ......................................................................... 9607.1
http.responses: ................................................................ 956
vusers.completed: .............................................................. 112
vusers.created: ................................................................ 155
vusers.created_by_name.퀴즈: ..................................................... 155
vusers.failed: ................................................................. 43
vusers.session_length:
  min: ......................................................................... 1015.4
  max: ......................................................................... 28764.8
  median: ...................................................................... 24107.7
  p95: ......................................................................... 26643.2
  p99: ......................................................................... 27181.5
```

응답 시간 성능이 떨어진 이유는, 리버스 프록시 용도로 필자가 설정한 nginx 외에 배포 플랫폼에서 클러스터 관리를 위해 내부적으로 nginx가 이미 사용되어 있기 때문이다.

- [_시스템 설계도 확인하기_](https://github.com/WithBible#%EC%8B%9C%EC%8A%A4%ED%85%9C-%EC%84%A4%EA%B3%84%EB%8F%84)
